TARGETS = 06 07 14 15 16 20 22_test 23 24 26 27_test 30_test 32_test 33_test

include ../makefile_template

20: 19_str_blob_ptr.o

22_test: 22_const_str_blob_ptr.o

27_test: 27_text_query.o

30_test: 30_text_query.o

32_test: 32_text_query_with_strblob.o ../common/str_blob.o

33_test: 33_text_query.o
